### ISSUE TITLE
Support for metric units

### ISSUE THREAD

**Issue by wanglongqi** [The111/GPXCreator#1]
Hi,

I do not know whether this project is still under maintenance, If so, is it possible to add an option to change the units from imperial units to metric units?

Regards,
Longqi

**Comment by The111** [comment]
This is something I always wanted to add, but I am pretty busy with my real job lately and may not get around to it any time soon. There is a forked version of this software that somebody else developed though, and he added a LOT of new features including what you want: http://wiki.openstreetmap.org/wiki/GpsMaster

**Comment by wanglongqi** [comment]
Thanks a lot! I will take a lot at that project.
